import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Movie Vault - Ultimate Streaming",
  description: "Generated by Movie Vault Agent",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="dark">
      <body className={`${inter.className} bg-[#0b0b0e] text-white min-h-screen flex flex-col md:flex-row`}>
        <Navbar />
        <div className="flex-1 md:pl-64 min-h-screen w-full">
          {children}
        </div>
      </body>
    </html>
  );
}